### ISSUE TITLE
Update comparison logic

### ISSUE THREAD

**Issue by aferrar** [ocmarin/ssd-bot#6]
Need to update comparison logic to handle appropriate cases for 'SSD' in submission title and other potential cases that may throw off match results. See [this thread](https://old.reddit.com/r/buildapcsales/comments/jua4n2/ssd_western_digital_1tb_sn720_ssd_m2_pcie_nvme_rw/) for example

**Comment by ocmarin** [comment]
Newest branch addresses the algorithm to prioritize differently, the mentioned post _should_ be handled correctly with it.
